`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 02.09.2026 18:22:39
// Design Name: 
// Module Name: tb_half_adder
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module tb_half_adder;
  reg A,B;
  wire S,C;
  
half_adder uut(
     .A(A),
     .B(B),
     .S(S),
     .C(C)
     ); 
     
 initial begin
 A=0;B=0;#10;
 A=0;B=1;#10;
 A=1;B=0;#10;
 A=1;B=1;#10;
 $finish;
 end
      
endmodule
